### ISSUE TITLE
Pinning the stactools version

### ISSUE THREAD

**Issue by cuttlefish** [stactools-packages/template#16]
Should we be using `==` or `~=`? Currently we're using the latter.
I suppose each package can do whatever it likes, but the default is likely to be influential.
I'm a bit torn as to which is more appropriate. Given how the docker build is currently functioning, it works as `==` since it pulls an image of the exact version. Because of that, I'm leaning towards using `==`. Thoughts?

**Comment by jbants** [comment]
If there is already precedent for it in the project, I'm keen to follow that.
+1
