### ISSUE TITLE
Syncing template updates with a package

### ISSUE THREAD

**Issue by scottyhq** [stactools-packages/template#23]
**Is your feature request related to a problem? Please describe.**

As updates are made to this template, how should a package creator bring in those changes? Some files don't matter so much, so at a minimum it would be nice to know which files should be kept up to date, and maybe this is just the CI workflows? `https://github.com/stactools-packages/template/tree/main/.github/workflows` 

**Describe the solution you'd like**

Add to the readme a subsection that lists files that packages should monitor for keeping up-to-date. 

**Describe alternatives you've considered**

I could also imagine a CI workflow that compares files in the template repository against a package repository or even suggests updates (https://github.com/AndreasAugustin/actions-template-sync), but that's probably more work.

**Comment by cuttlefish** [comment]
The way the Docker images work has changed upstream. At the very least the images being pulled need to be changed to `ghcr.io/stac-utils/stactools`. Likely the whole of the `scripts` and `docker` dirs need to be synced.

**Comment by cuttlefish** [comment]
I guess something like `git submodules` could work here... but I'd **really** rather not.

**Comment by gadomski** [comment]
> I guess something like git submodules could work here... but I'd really rather not.

Agreed, it takes a lot of convincing to get me onboard with a submodule solution :-)

It's awkward, to be sure. Taking a step back, how bad _is_ it if packages fall out-of-sync with the latest template? If the code works and you can publish to PyPI, is it that big of a deal if some of the scripts aren't the latest and greatest?

**Comment by cuttlefish** [comment]
> It's awkward, to be sure. Taking a step back, how bad _is_ it if packages fall out-of-sync with the latest template? If the code works and you can publish to PyPI, is it that big of a deal if some of the scripts aren't the latest and greatest?

It's fine most of the time. But in this specific scenario the Docker registry has changed. It should continue to work for the old config as long as they don't try to update `stactools`. (I think DockerHub is also dropping images after a certain amount of time, so I guess it might fail then as well)

**Comment by scottyhq** [comment]
I just wanted to make sure the CI checks for the package I'm working on matched the CI checks for other packages and didn't want to comb through and manually add files that have been changed. Here is the solution I came up with https://github.com/stactools-packages/sentinel1/blob/main/.github/workflows/sync-template.yml. Note though that it requires a package repository owner to add a personal access token with appropriate permissions.

**Comment by cuttlefish** [comment]
I think you'll need to run `scripts/rename` on the repo before you copy the files over. It currently depends on the directory name of the repo to be set to the correct name.
We could probably restructure things to simplify this.

**Comment by gadomski** [comment]
@scottyhq this looks cool, do we need to make a change or two to some "sync'd" files to test or have you already done that?

**Comment by scottyhq** [comment]
@gadomski yes - as mentioned by @cuttlefish you have to run the `scripts/rename`. I modified the github action to be a bit more generic, but then ran into https://github.com/stactools-packages/template/issues/25, so I ended up running that `rename` script locally on a mac to setup the correct names in the docker folder.

Also note the action I'm using is pretty simplistic as it just copies template files from `docker/` `scripts/` and `.github/workflows`, so won't account for renaming or deleting files. But if you think it's helpful we could put it into this template after the rename script gets sorted to run on linux.

**Comment by cuttlefish** [comment]
#27 changes the `docker/` scripts so that they now source variables from `./docker_env`. This should allow us to directly copy the `scripts` and `docker` directories when updating repos.
For `docker_env` we can either leave that as something requiring manual updates, or it should be replaceable once `scripts/rename` has been run.

**Comment by gadomski** [comment]
Coming back to this _years_ later, I think this problem is partially solved by making this template repo as simple as possible, with the goal of reducing the number of changes a downstream should have to uptake. We've got a pretty decent idea of the minimum set of things a **stactools-package** needs to be useful, and anything else should be pushed not to this template repo but to **stactools** or another repo (e.g. https://github.com/gadomski/antimeridian).

**Comment by gadomski** [comment]
I'm going to close this as wontfix, as sync-ing all new changes to old repos would be a lot of work w/ very little benefit, IMO. This repo can serve as a point of reference for "best practices" (e.g. what the conda environment file should look like).
