### ISSUE TITLE
Rename script is overwriting the `stactools-packages` group name

### ISSUE THREAD

**Issue by cuttlefish** [stactools-packages/template#24]
The rename script is mangling `docker/env`. `sed` implementation of regex doesn't support lookahead. This makes it difficult for it to recognize the difference between `stactools-package` and `stactools-packages`. The former should be rewritten, the latter should not. [I may be missing a simple option here]

As I see it we can:
- Switch to more robust regex tool. The downside is that we now introduce a dependency that might not be properly installed.
- Change the token to be rewritten from `package` to something else that won't conflict. `template`? We might hit similar problems down the road. It's nice having a name that is still valid syntactically because we can test the template repo on its own.
- Switch to a proper templating system. That seems likely to be too much work. Although it might help with a more robust solution for #23. At that point I'm not sure if a GitHub template repo is even the correct way to handle it... 🤷

**Comment by gadomski** [comment]
Could we do a really hackey "move out of the way" sort of thing, e.g.
1. Change `stactools-packages` to `stringthatwellchangebacklater`
2. Update all `stactools-package`
3. Change `stringthatwellchangbacklater` to `stactools-packages`

**Comment by cuttlefish** [comment]
That's definitely an option 😆 I forgot to included it.
I guess I'd rather change the `package` magic word, since it conflicts with other things as well.
Neither solution is stellar, but I don't think anything more complex is warranted at the moment.

**Comment by gadomski** [comment]
>  I guess I'd rather change the package magic word, since it conflicts with other things as well.

Worksforme!

**Comment by cuttlefish** [comment]
👍 I'll take a look at it this afternoon
