### ISSUE TITLE
rename script doesn't work on linux

### ISSUE THREAD

**Issue by justinfisk** [stactools-packages/template#25]
while we are looking at other `rename` script changes, the rename script fails on linux.

first here:
https://github.com/stactools-packages/template/blob/23ab7621777a9665a92a8ea6f21a20307ef09930/scripts/rename#L6
with 
```
./scripts/rename: 6: Bad substitution
```
This line is bash specific. On os x, `sh` is handled by `bash`, but on debian/ubuntu, `sh` is handled by `dash`. Switching to `#!/usr/bin/env bash` would solve. 

second, the `sed` command form seems to be os x (or bsd?) specific, and these lines:
https://github.com/stactools-packages/template/blob/23ab7621777a9665a92a8ea6f21a20307ef09930/scripts/rename#L16
fail with 
```
sed: can't read : No such file or directory
```

something like 
```
if [[ "$OSTYPE" == "darwin"* ]]; then
    sedopt"-i ''"
else
    sedopt="-i"
fi
```
and changing the sed lines to
```
    sed ${sedopt} -e "s/stactools-package/stactools-${name}/g" $file
    sed ${sedopt} -e "s/stactools\.package/stactools.${underscore_name}/g" $file
    sed ${sedopt} -e "s/stactools_package/stactools_${underscore_name}/g" $file
    sed ${sedopt} -e "s;stactools/package;stactools/${underscore_name};g" $file
```
would work, but there may be something cleaner

**Comment by cuttlefish** [comment]
This is very timely. I just ran across the same problems last night.
Thanks for #26! I'll get it merged in.
