### ISSUE TITLE
Separate tests and formatting

### ISSUE THREAD

**Issue by jbants** [stactools-packages/template#35]
This seems incorrect in the template - we shouldn't run formatting as part of tests.

_Originally posted by @lossyrob in https://github.com/stactools-packages/jrc-gsw/pull/6#discussion_r677872810_

Formatting standards can change over time and it should not imply the code is borked.  - Paudley

**Comment by lossyrob** [comment]
Yep - `scripts/lint` that is run as part of CI will check that formatting is correct. `scripts/format` will format the code - in the case CI it's not checking anything, it's just formatting code before running tests, which is a no-op in CI but can be unexpected for someone running `scripts/test` locally
