### ISSUE TITLE
Package for Sentinel-3 OLCI/SLSTR

### ISSUE THREAD

**Issue by maximlamare** [stactools-packages/template#46]
@cuttlefish or @lossyrob 

Our team (@chorng) has added an other sensor as a stactools package. If you see fit, could you help integrate this one too please?

https://github.com/chorng/sentinel3

**Comment by cuttlefish** [comment]
I've added the repo but haven't had a chance to do a review.
https://github.com/stactools-packages/sentinel3
@chorng and @maximlamare should have write access to the repo.

**Comment by cuttlefish** [comment]
Thanks for your contribution! 🎊
