### ISSUE TITLE
Package for Sentinel-5P level 2 products

### ISSUE THREAD

**Issue by chorng** [stactools-packages/template#50]
@cuttlefish or @lossyrob

Our team (@maximlamare and I) has added part of Sentinel-5P level 2 products as a stactools package. If you see fit, could you help integrate this one too please?

Since all data is written in netCDF4 files so this package required [`netCDF4`](https://pypi.org/project/netCDF4/) library. The following is a list of products which can be processed by this package:
- `L2__AER_AI_`
- `L2__AER_LH_`
- `L2__CH4____`
- `L2__CLOUD__`
- `L2__CO_____`
- `L2__HCHO___`
- `L2__NO2____`
- `L2__O3_TCL_`
- `L2__O3_____`
- `L2__SO2____`
- `L2__NP_BD3_`
- `L2__NP_BD6_`
- `L2__NP_BD7_`

Package for Sentinel-5P: https://github.com/chorng/sentinel5p

**Comment by lossyrob** [comment]
@chorng just getting around to seeing this, sorry for the delay! Can you make me an admin on that repo, so I can transfer it to the `stactools-packages` org? Thanks!

**Comment by chorng** [comment]
@lossyrob I've sent you an invitation.

**Comment by lossyrob** [comment]
@chorng - thanks, I accepted but it doesn't seem like I have admin privileges on the repo (no repo Setting show up for me). Can you check to make sure I have the right permissions? Thanks!

**Comment by cuttlefish** [comment]
Sorry I missed this. Let me know if I can be of any help.

**Comment by lossyrob** [comment]
@cuttlefish what was your process for moving over the last repo? The way I know how is to become an admin on the target repo, and then make the transfer - let me know if there's an easier/different process you've followed before.

**Comment by cuttlefish** [comment]
@lossyrob Previously I did the less elegant "make new repo, push contents of old repo to new repo".
Transferring the repo would be nice, but given that so far issues and such haven't been used I don't think we're losing too much if we just create a new repo.

**Comment by chorng** [comment]
@lossyrob It seems that I can't adjust the permission of collaborators with a simple user account (see [here](https://stackoverflow.com/questions/64478636/how-to-give-admin-access-to-private-repository-when-there-is-no-role-options)). There's no role options showed up for me.

**Comment by lossyrob** [comment]
Got it - in that case I'll do what @cuttlefish did for the other repo and just push a new repo up in stactools-packages. Will close this issue once complete.

**Comment by lossyrob** [comment]
I created https://github.com/stactools-packages/sentinel5p and added @chorng as a maintainer, as well as gave @jmakovecki write access. You should be able to add others and adjust roles as needed.
