### ISSUE TITLE
Add script to set the package name

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/template#6]
Manually going through and changing `stactools-package` to `stactools-foo` is a pain. We should provide a script to automate this.

**Comment by cuttlefish** [comment]
Possibly something like this? https://stefanbuck.com/blog/repository-templates-meets-github-actions
There seem to be several alternatives, I've only briefly skimmed it.

**Comment by gadomski** [comment]
Interesting, I hadn't thought about using Github Actions to complete the template setup. If you wanted to try to setup an action that used the `scripts/rename` in #10 I'd be open to it. I wonder if it's worth the additional complexity, though -- running the rename script once isn't that bad.

**Comment by cuttlefish** [comment]
Yeah, I'm not sure managing the complexity is worth it either. I'm happy with just running the script once.
