### ISSUE TITLE
Getting stactools version for Docker fails

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/template#70]
**Describe the bug**

If you set the stactools version in setup.cfg to something like `stactools == 0.4.*` the Docker build in CI fails:

> ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "ghcr.io/stac-utils/stactools:0.4.*": invalid reference format
> Error: buildx failed with: ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "ghcr.io/stac-utils/stactools:0.4.*": invalid reference format

By default the dependency is set to `stactools >= 0.4.0`, but that might not be the best idea as this may lead to issues when breaking changes are occuring in like 1.0.0 or so...

Edit: It also fails if I add a comment after the version number, e.g. `stactools >= 0.4.0 # leave as is` doesn't work.

**To reproduce**

See above.

**Expected behavior**

No error.

**Comment by gadomski** [comment]
I believe this is fixed by #75 (aka remove the offending stuff).
