### ISSUE TITLE
mypy error on python 3.10.7+

### ISSUE THREAD

**Issue by wildintellect** [stactools-packages/template#71]
**Describe the bug**
A recent [mypy bug](https://github.com/python/mypy/issues/13627) leads to issues with python 3.10
When running `mypy` < 0.981 there's a bug that results in.

**To reproduce**
Run `pre-commit` in a python 3.10.7+ environment

**Expected behavior**
mypy should pass the same in all python versions used

**Screenshots and shell session dumps**
``mypy.....................................................................Failed
- hook id: mypy
- exit code: 2
```
/home/nonroot/.cache/pre-commit/repomdxkdhlc/py_env-python3.11/lib/python3.11/site-packages/numpy/__init__.pyi:638: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

**Additional context**
Offending line https://github.com/stactools-packages/template/blob/8b15971a9f1fae7933b0e45aac8d59188daf5db5/.pre-commit-config.yaml#L20 

The easiest fix is to bump the `mypy` version specified in the `.pre-commit-config.yaml`. However @chuckwondo pointed out this means we have to keep tracking versions in the yaml instead of the same place as other parts of the project like `requirements-dev.txt` We'll put up a PR later today with a proposed fix.

**Comment by gadomski** [comment]
Fixed by #75.
