### ISSUE TITLE
[RFC] Remove docker images

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/template#74]
As a consumer and producer of **stactools-packages**, I rarely if ever use the docker images. If I do need to use my **stactools-package** in a containerized environment, it's easy enough to install it like a normal Python package from PyPI. As a **stactools-package** maintainer, I find I spend a non-insigificant amount of time debugging issues with the (relatively complex) Docker setup, e.g. the CI breakages in https://github.com/stactools-packages/template/pull/73.

If you use the Docker images for **stactools-packages**, please chime in with how you're using them. At the least, I'd like to simplify the Docker builds in this template to reduce the amount of time spent fixing them, and at the most, I'd like to remove them.

**Comment by wildintellect** [comment]
I use them to setup my development environment in VSCode, but suspect I could switch to a standard miniconda environment and run the package setup/install.

**Comment by gadomski** [comment]
Gotcha. If we just need a development environment, we could _for sure_ strip away a lot of the publishing magic, and just provide a Dockerfile, yes?

**Comment by matthewhanson** [comment]
I agree they are useful for development, but I'd be surprised if during actual use in an app that users aren't creating their own custom Docker images.
